# 모델 이름 바꾸기!!!!!!!

custom:
  model_arch: BaseModel
  preprocess: base_preprocess

path:
  train_path: ../data/train.csv
  dev_path: ../data/dev.csv
  test_path: ../data/dev.csv
  predict_path: ../data/test.csv

data:
  shuffle: True
  augmentation: base_augmentation

model:
  model_name: klue/roberta-small
  saved_name: roberta-small-base

train:
  gpus: 1
  batch_size: 16
  max_epoch: 10
  learning_rate: 1e-5
  logging_step: 1